version: '3'

services:
  frontend:
    build:
      container_name: app_frontend
      build: ./frontend
      ports:
        - 3000:3000
      working_dir: /app-frontend

  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: dev
    volumes: ./backend/src:/app-backend/src
    depends_on:
      - postgres
    environment:
      APP_PORT: 3001
      JWT_SECRET: jwt_secret
      POSTGRES_USER: root
      POSTGRES_PASS: root
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  postgres:
    image: postgres
    container_name: postgres_database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
    restart: 'always'
